com:
  juliuskrah:
    cron: 0 20-58 09 ? JAN MON-FRI
    inline-cron: 0 20-59 09-21 ? JAN-APR MON-SAT
    mail:
      message-subject: Tutorial Subject
      personal: Julius from JuliusKrah.com
      sender: ${MAIL_USERNAME:juliuskrah@example.org}
      recipients:
      - username: Julius
        email: juliuskrah@example.com
    report-location: classpath:reports
    storage-location: file:${user.home}/juliuskrah.com
spring:
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:juliuskrah@example.org}
    password: ${MAIL_PASSWORD:1234567890}
    test-connection: false
    properties:
      mail.smtp.starttls.enable: true