com:
  juliuskrah:
    cron: 0 48-58 20 ? APR MON-FRI
    mail:
      message-subject: Tutorial Subject
      personal: Julius from JuliusKrah.com
      sender: ${MAIL_USERNAME}
      recipients:
      - username: Julius
        email: juliuskrah@hotmail.com
    report-location: classpath:reports
    storage-location: file:${user.home}/juliuskrah.com
spring:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    test-connection: true
    properties:
      mail.smtp.starttls.enable: true